const MOVIES = [
  {
    id: 'sitaramam',
    title: 'Sita Ramam',
    year: 2022,
    genre: 'Romance · Drama',
    rating: 'U',
    status: 'new',
    poster: 'assets/posters/sitaramam.jpg',
  },
  {
    id: 'kalki2898ad',
    title: 'Kalki 2898 AD',
    year: 2024,
    genre: 'Sci-Fi · Action',
    rating: 'UA',
    status: 'new',
    poster: 'assets/posters/kalki2898ad.jpg',
  },
  {
    id: 'devara',
    title: 'Devara: Part 1',
    year: 2024,
    genre: 'Action · Drama',
    rating: 'UA',
    status: 'new',
    poster: 'assets/posters/devara.jpg',
  },
  {
    id: 'hanuman',
    title: 'Hanu-Man',
    year: 2024,
    genre: 'Fantasy · Action',
    rating: 'U',
    status: 'upcoming',
    poster: 'assets/posters/hanuman.jpeg',
  },
  {
    id: 'pushpa1',
    title: 'Pushpa: The Rise',
    year: 2021,
    genre: 'Action · Drama',
    rating: 'UA',
    status: 'other',
    poster: 'assets/posters/pushpa1.jpg',
  },
  {
    id: 'baahubali2',
    title: 'Baahubali 2: The Conclusion',
    year: 2017,
    genre: 'Action · Epic',
    rating: 'UA',
    status: 'other',
    poster: 'assets/posters/baahubali2.jpg',
  },
  {
    id: 'alavaikunthapurramuloo',
    title: 'Ala Vaikunthapurramuloo',
    year: 2020,
    genre: 'Comedy · Drama',
    rating: 'UA',
    status: 'other',
    poster: 'assets/posters/alavaikunthapurramuloo.jpeg',
  },
  {
    id: 'rrr',
    title: 'RRR',
    year: 2022,
    genre: 'Action · Drama',
    rating: 'UA',
    status: 'other',
    poster: 'assets/posters/rrr.jpg',
  },
];
